/*
 * This source file was generated by the Gradle 'init' task (and changed manually)
 */
package Wheelie;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        DummyLibrary classUnderTest = new DummyLibrary();
        assertTrue(classUnderTest.DummyMethod(), "someLibraryMethod should return 'true'");
    }
}
